"""Incrementar el espacio del hash para los pines de los usuarios

Revision ID: 0644d175328e
Revises: a994d26f0d63
Create Date: 2025-04-03 19:58:14.463837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0644d175328e'
down_revision = 'a994d26f0d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('pin',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('pin',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###
