"""Agregar campo moneda y fecha_creacion con valores nulos inicialmente

Revision ID: 0cc1e67c2f6e
Revises: 0644d175328e
Create Date: 2025-04-19 13:19:25.601946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc1e67c2f6e'
down_revision = '0644d175328e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('ingreso', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moneda', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('moneda')

    with op.batch_alter_table('ingreso', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
