"""Initial migration for SQLite

Revision ID: 52e1427474a2
Revises: 
Create Date: 2025-04-22 16:48:31.157628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e1427474a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('pin', sa.String(length=128), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('login_attempts', sa.Integer(), nullable=True),
    sa.Column('lockout_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_lockout_until'), ['lockout_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_login_attempts'), ['login_attempts'], unique=False)

    op.create_table('billetera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('cuenta', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingreso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('cuenta', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingreso')
    op.drop_table('gasto')
    op.drop_table('billetera')
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_login_attempts'))
        batch_op.drop_index(batch_op.f('ix_profile_lockout_until'))

    op.drop_table('profile')
    # ### end Alembic commands ###
