"""Agregar campo incluir_en_balance a billeteras

Revision ID: 6aeae8d84091
Revises: 9e27e96601cf
Create Date: 2025-05-26 01:06:13.850825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aeae8d84091'
down_revision = '9e27e96601cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billetera', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incluir_en_balance', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billetera', schema=None) as batch_op:
        batch_op.drop_column('incluir_en_balance')

    # ### end Alembic commands ###
