"""Agregar modelo SalarioSemanal para gestion de salarios semanales

Revision ID: 9b605c2b6e86
Revises: 6aeae8d84091
Create Date: 2025-06-06 11:49:00.762040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b605c2b6e86'
down_revision = '6aeae8d84091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salario_semanal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('salario_bruto', sa.Float(), nullable=False),
    sa.Column('impuestos', sa.Float(), nullable=False),
    sa.Column('housing', sa.Float(), nullable=False),
    sa.Column('salario_neto', sa.Float(), nullable=False),
    sa.Column('gastos_comida', sa.Float(), nullable=False),
    sa.Column('gastos_variables', sa.Float(), nullable=False),
    sa.Column('balance_semanal', sa.Float(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salario_semanal')
    # ### end Alembic commands ###
