"""Agrega seguridad a la db

Revision ID: a51b931449f8
Revises: e064edd3699d
Create Date: 2025-04-03 13:38:41.980191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51b931449f8'
down_revision = 'e064edd3699d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lockout_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('lockout_until')
        batch_op.drop_column('login_attempts')

    # ### end Alembic commands ###
