"""Agrega optimizacion

Revision ID: a994d26f0d63
Revises: a51b931449f8
Create Date: 2025-04-03 13:43:23.488706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a994d26f0d63'
down_revision = 'a51b931449f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_lockout_until'), ['lockout_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_login_attempts'), ['login_attempts'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_login_attempts'))
        batch_op.drop_index(batch_op.f('ix_profile_lockout_until'))

    # ### end Alembic commands ###
